INSERT INTO paises VALUES
(gen_random_uuid(), 'Australia'),
(gen_random_uuid(), 'Austria'),
(gen_random_uuid(), 'Azerbaiyan'),
(gen_random_uuid(), 'Anguilla'),
(gen_random_uuid(), 'Argentina'),
(gen_random_uuid(), 'Armenia'),
(gen_random_uuid(), 'Bielorrusia'),
(gen_random_uuid(), 'Belice'),
(gen_random_uuid(), 'Belgica'),
(gen_random_uuid(), 'Bermudas'),
(gen_random_uuid(), 'Bulgaria'),
(gen_random_uuid(), 'Brasil'),
(gen_random_uuid(), 'Reino Unido'),
(gen_random_uuid(), 'Hungria'),
(gen_random_uuid(), 'Vietnam'),
(gen_random_uuid(), 'Haiti'),
(gen_random_uuid(), 'Guadalupe'),
(gen_random_uuid(), 'Alemania'),
(gen_random_uuid(), 'Paises Bajos'),
(gen_random_uuid(), 'Grecia'),
(gen_random_uuid(), 'Georgia'),
(gen_random_uuid(), 'Dinamarca'),
(gen_random_uuid(), 'Egipto'),
(gen_random_uuid(), 'Israel'),
(gen_random_uuid(), 'India'),
(gen_random_uuid(), 'Iran'),
(gen_random_uuid(), 'Irlanda'),
(gen_random_uuid(), 'España'),
(gen_random_uuid(), 'Italia'),
(gen_random_uuid(), 'Kazajstan'),
(gen_random_uuid(), 'Camerun'),
(gen_random_uuid(), 'Canada'),
(gen_random_uuid(), 'Chipre'),
(gen_random_uuid(), 'Kirguistan'),
(gen_random_uuid(), 'China'),
(gen_random_uuid(), 'Costa Rica'),
(gen_random_uuid(), 'Kuwait'),
(gen_random_uuid(), 'Letonia'),
(gen_random_uuid(), 'Libia'),
(gen_random_uuid(), 'Lituania'),
(gen_random_uuid(), 'Luxemburgo'),
(gen_random_uuid(), 'Mexico'),
(gen_random_uuid(), 'Moldavia'),
(gen_random_uuid(), 'Monaco'),
(gen_random_uuid(), 'Nueva Zelanda'),
(gen_random_uuid(), 'Noruega'),
(gen_random_uuid(), 'Polonia'),
(gen_random_uuid(), 'Portugal'),
(gen_random_uuid(), 'Reunion'),
(gen_random_uuid(), 'Rusia'),
(gen_random_uuid(), 'El Salvador'),
(gen_random_uuid(), 'Eslovaquia'),
(gen_random_uuid(), 'Eslovenia'),
(gen_random_uuid(), 'Surinam'),
(gen_random_uuid(), 'Estados Unidos'),
(gen_random_uuid(), 'Tadjikistan'),
(gen_random_uuid(), 'Turkmenistan'),
(gen_random_uuid(), 'Islas Turcas y Caicos'),
(gen_random_uuid(), 'Turquia'),
(gen_random_uuid(), 'Uganda'),
(gen_random_uuid(), 'Uzbekistan'),
(gen_random_uuid(), 'Ucrania'),
(gen_random_uuid(), 'Finlandia'),
(gen_random_uuid(), 'Francia'),
(gen_random_uuid(), 'Republica Checa'),
(gen_random_uuid(), 'Suiza'),
(gen_random_uuid(), 'Suecia'),
(gen_random_uuid(), 'Estonia'),
(gen_random_uuid(), 'Corea del Sur'),
(gen_random_uuid(), 'Japon'),
(gen_random_uuid(), 'Croacia'),
(gen_random_uuid(), 'Rumania'),
(gen_random_uuid(), 'Hong Kong'),
(gen_random_uuid(), 'Indonesia'),
(gen_random_uuid(), 'Jordania'),
(gen_random_uuid(), 'Malasia'),
(gen_random_uuid(), 'Singapur'),
(gen_random_uuid(), 'Taiwan'),
(gen_random_uuid(), 'Bosnia y Herzegovina'),
(gen_random_uuid(), 'Bahamas'),
(gen_random_uuid(), 'Chile'),
(gen_random_uuid(), 'Colombia'),
(gen_random_uuid(), 'Islandia'),
(gen_random_uuid(), 'Corea del Norte'),
(gen_random_uuid(), 'Macedonia'),
(gen_random_uuid(), 'Malta'),
(gen_random_uuid(), 'Pakistan'),
(gen_random_uuid(), 'Papua-Nueva Guinea'),
(gen_random_uuid(), 'Peru'),
(gen_random_uuid(), 'Filipinas'),
(gen_random_uuid(), 'Arabia Saudita'),
(gen_random_uuid(), 'Tailandia'),
(gen_random_uuid(), 'Emiratos Arabes Unidos'),
(gen_random_uuid(), 'Groenlandia'),
(gen_random_uuid(), 'Venezuela'),
(gen_random_uuid(), 'Zimbabwe'),
(gen_random_uuid(), 'Kenia'),
(gen_random_uuid(), 'Algeria'),
(gen_random_uuid(), 'Libano'),
(gen_random_uuid(), 'Botsuana'),
(gen_random_uuid(), 'Tanzania'),
(gen_random_uuid(), 'Namibia'),
(gen_random_uuid(), 'Ecuador'),
(gen_random_uuid(), 'Marruecos'),
(gen_random_uuid(), 'Ghana'),
(gen_random_uuid(), 'Siria'),
(gen_random_uuid(), 'Nepal'),
(gen_random_uuid(), 'Mauritania'),
(gen_random_uuid(), 'Seychelles'),
(gen_random_uuid(), 'Paraguay'),
(gen_random_uuid(), 'Uruguay'),
(gen_random_uuid(), 'Congo (Brazzaville)'),
(gen_random_uuid(), 'Cuba'),
(gen_random_uuid(), 'Albania'),
(gen_random_uuid(), 'Nigeria'),
(gen_random_uuid(), 'Zambia'),
(gen_random_uuid(), 'Mozambique'),
(gen_random_uuid(), 'Angola'),
(gen_random_uuid(), 'Sri Lanka'),
(gen_random_uuid(), 'Etiopia'),
(gen_random_uuid(), 'Tunez'),
(gen_random_uuid(), 'Bolivia'),
(gen_random_uuid(), 'Panama'),
(gen_random_uuid(), 'Malawi'),
(gen_random_uuid(), 'Liechtenstein'),
(gen_random_uuid(), 'Bahrein'),
(gen_random_uuid(), 'Barbados'),
(gen_random_uuid(), 'Chad'),
(gen_random_uuid(), 'Man, Isla de'),
(gen_random_uuid(), 'Jamaica'),
(gen_random_uuid(), 'Mali'),
(gen_random_uuid(), 'Madagascar'),
(gen_random_uuid(), 'Senegal'),
(gen_random_uuid(), 'Togo'),
(gen_random_uuid(), 'Honduras'),
(gen_random_uuid(), 'Republica Dominicana'),
(gen_random_uuid(), 'Mongolia'),
(gen_random_uuid(), 'Irak'),
(gen_random_uuid(), 'Sudafrica'),
(gen_random_uuid(), 'Aruba'),
(gen_random_uuid(), 'Gibraltar'),
(gen_random_uuid(), 'Afganistan'),
(gen_random_uuid(), 'Andorra'),
(gen_random_uuid(), 'Antigua y Barbuda'),
(gen_random_uuid(), 'Bangladesh'),
(gen_random_uuid(), 'Benin'),
(gen_random_uuid(), 'Butan'),
(gen_random_uuid(), 'Islas Virgenes Britanicas'),
(gen_random_uuid(), 'Brunei'),
(gen_random_uuid(), 'Burkina Faso'),
(gen_random_uuid(), 'Burundi'),
(gen_random_uuid(), 'Camboya'),
(gen_random_uuid(), 'Cabo Verde'),
(gen_random_uuid(), 'Comores'),
(gen_random_uuid(), 'Congo (Kinshasa)'),
(gen_random_uuid(), 'Cook, Islas'),
(gen_random_uuid(), 'Costa de Marfil'),
(gen_random_uuid(), 'Djibouti, Yibuti'),
(gen_random_uuid(), 'Timor Oriental'),
(gen_random_uuid(), 'Guinea Ecuatorial'),
(gen_random_uuid(), 'Eritrea'),
(gen_random_uuid(), 'Feroe, Islas'),
(gen_random_uuid(), 'Fiyi'),
(gen_random_uuid(), 'Polinesia Francesa'),
(gen_random_uuid(), 'Gabon'),
(gen_random_uuid(), 'Gambia'),
(gen_random_uuid(), 'Granada'),
(gen_random_uuid(), 'Guatemala'),
(gen_random_uuid(), 'Guernsey'),
(gen_random_uuid(), 'Guinea'),
(gen_random_uuid(), 'Guinea-Bissau'),
(gen_random_uuid(), 'Guyana'),
(gen_random_uuid(), 'Jersey'),
(gen_random_uuid(), 'Kiribati'),
(gen_random_uuid(), 'Laos'),
(gen_random_uuid(), 'Lesotho'),
(gen_random_uuid(), 'Liberia'),
(gen_random_uuid(), 'Maldivas'),
(gen_random_uuid(), 'Martinica'),
(gen_random_uuid(), 'Mauricio'),
(gen_random_uuid(), 'Myanmar'),
(gen_random_uuid(), 'Nauru'),
(gen_random_uuid(), 'Antillas Holandesas'),
(gen_random_uuid(), 'Nueva Caledonia'),
(gen_random_uuid(), 'Nicaragua'),
(gen_random_uuid(), 'Niger'),
(gen_random_uuid(), 'Norfolk Island'),
(gen_random_uuid(), 'Oman'),
(gen_random_uuid(), 'Isla Pitcairn'),
(gen_random_uuid(), 'Qatar'),
(gen_random_uuid(), 'Ruanda'),
(gen_random_uuid(), 'Santa Elena'),
(gen_random_uuid(), 'San Cristobal y Nevis'),
(gen_random_uuid(), 'Santa Lucia'),
(gen_random_uuid(), 'San Pedro y Miquelon'),
(gen_random_uuid(), 'San Vincente y Granadinas'),
(gen_random_uuid(), 'Samoa'),
(gen_random_uuid(), 'San Marino'),
(gen_random_uuid(), 'San Tome y Principe'),
(gen_random_uuid(), 'Serbia y Montenegro'),
(gen_random_uuid(), 'Sierra Leona'),
(gen_random_uuid(), 'Islas Salomon'),
(gen_random_uuid(), 'Somalia'),
(gen_random_uuid(), 'Sudan'),
(gen_random_uuid(), 'Swazilandia'),
(gen_random_uuid(), 'Tokelau'),
(gen_random_uuid(), 'Tonga'),
(gen_random_uuid(), 'Trinidad y Tobago'),
(gen_random_uuid(), 'Tuvalu'),
(gen_random_uuid(), 'Vanuatu'),
(gen_random_uuid(), 'Wallis y Futuna'),
(gen_random_uuid(), 'Sahara Occidental'),
(gen_random_uuid(), 'Yemen'),
(gen_random_uuid(), 'Puerto Rico');


INSERT INTO estados VALUES 
(gen_random_uuid(), 'Distrito Capital', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Merida', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Tachira', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Trujillo', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Vargas', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Miranda', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Aragua', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Carabobo', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Falcon', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Lara', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Yaracuy', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Amazonas', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Bolivar', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Delta Amacuro', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Nueva Esparta', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Dependencias federales', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Apure', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Barinas', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Cojedes', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Guarico', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Portuguesa', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Anzoategui', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Monagas', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Sucre', (SELECT uuid FROM paises WHERE nombre = 'Venezuela')),
(gen_random_uuid(), 'Zulia', (SELECT uuid FROM paises WHERE nombre = 'Venezuela'));

INSERT INTO ciudades VALUES
(gen_random_uuid(), 'Caracas', (SELECT uuid FROM estados WHERE nombre = 'Distrito Capital')),
(gen_random_uuid(), 'San Antonio', (SELECT uuid FROM estados WHERE nombre = 'Miranda')),
(gen_random_uuid(), 'Los Teques', (SELECT uuid FROM estados WHERE nombre = 'Miranda')),
(gen_random_uuid(), 'Maracay', (SELECT uuid FROM estados WHERE nombre = 'Aragua')),
(gen_random_uuid(), 'La Victoria', (SELECT uuid FROM estados WHERE nombre = 'Aragua'));